# Generated by Django 5.0.3 on 2025-08-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condidatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('entreprise', models.CharField(max_length=150)),
                ('localisation', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
