# Generated by Django 5.0.3 on 2025-09-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condidatures', '0003_candidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
