# Generated by Django 5.0.3 on 2025-09-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condidatures', '0004_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adaptabilite_score',
            field=models.FloatField(default=0.0, help_text="Score d'adaptabilité (0-10)"),
        ),
        migrations.AddField(
            model_name='profile',
            name='engagement_communautaire',
            field=models.IntegerField(default=0, help_text="Heures d'engagement communautaire"),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_internationale',
            field=models.IntegerField(default=0, help_text="Nombre d'années d'expérience internationale"),
        ),
        migrations.AddField(
            model_name='profile',
            name='innovation_score',
            field=models.FloatField(default=0.0, help_text="Score d'innovation (0-10)"),
        ),
        migrations.AddField(
            model_name='profile',
            name='leadership_score',
            field=models.FloatField(default=0.0, help_text='Score de leadership (0-10)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='motivation_score',
            field=models.FloatField(default=0.0, help_text='Score de motivation (0-10)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='niveau_anglais',
            field=models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('bilingue', 'Bilingue')], default='intermediaire', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='participation_projets',
            field=models.IntegerField(default=0, help_text='Nombre de projets participés'),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_qualite',
            field=models.FloatField(default=0.0, help_text='Qualité du portfolio (0-10)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recommandation_prof',
            field=models.IntegerField(default=0, help_text='Nombre de recommandations professeurs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stage_anterieur',
            field=models.BooleanField(default=False, help_text='A déjà effectué un stage'),
        ),
    ]
